### ISSUE TITLE
Couple of installation issues and fixes on the raspberrypi

### ISSUE THREAD

**Issue by klakka** [raspiweather/raspiweather#1]
1 Line four of pips.req needs to be deleted and manually install using sudo apt-get install python-usb
2 Once installed go into sites-enabled and sudo nano raspiweather, once in there do the following :- 

Replace
include fastcgi_params;
With
include fastcgi.conf;

This will stop the blank page appearing.

What I need to find out is a fix for the working folder /tmp/weather after a restart the folder gets deleted and pwwys will not start until this is created.

Also would love a few pointers on how to make extra templates. for instance the year min and max temp each month graph. Plus widgets for max / min temp and date, maximum wind gust.

Oh and how to change from C to F for my old man ;-) 

Love it though, really impressed and very nippy at rendering the pages.

Congrats

**Comment by shreddedbacon** [comment]
Hey, thanks for taking the time to join github and raise the issue.

1) I didn't have any issues with the pips.req file on the raspberry pis that I installed on during my initial testing. But I may have already had python-usb installed. I'll look into and do some testing with this though. All my test installs did start out as barebones raspbian installs.

2) I'll look at this as well. I'm not sure what blank page you're talking about though, can you give me more information?

I haven't noticed the issue with /tmp/weather either, I'll look into it during more tests.

Regarding templates, the templates are all based on the templates code for PYWWS which can be found here:
http://pythonhosted.org/pywws/en/html/api/pywws.Template.html
I have done some extensive modifications around the graphs though, as these are not normally done in PYWWS templates so this could be confusing if you're trying to generate a custom chart. I did start (created a folder called wiki...) documenting templates a bit more indepth but as this project is just that still, a project, I haven't had a lot of time to dedicate to it. I'm more than happy to help you out in creating one though if you have some ideas of data you want to plot.

Regarding additional widgets, I hadn't gone too far into that. I will look at it as an option though. I didn't want to clutter the main tab as its more of an at a glance look.

For changing from C to F, if you're that way inclined ;P, you can modify the widgets template by manually editing the code that generates them, and using PYWWS functions (http://pythonhosted.org/pywws/en/html/api/pywws.conversions.html) you can do the change:
`su to weather user`
`nano ~/templates/widgets.txt`
look for the one you want to change

For example: 
`#temp_out "%.1f" "-"#`
would become
`#temp_f(temp_out) "%.1f" "-"#`

Once you've done that, you then go to the raspiweather web gui on the raspberry pi and go to Settings(GEAR)->Widgets Configuration, then select the widget you want to change from C to F and change the icon from wi-celcius to wi-fahrenheit

I'm also interested in how you found this project too, as I haven't really told anyone about it.

**Comment by klakka** [comment]
Hi thanks for the quick response, ive tried installing twice now on each attempt after restarting nginx, the only page you get is a blank white page, it took me hours to work out what it was. There's no errors anywhere so I went on the hunt for an answer:-
http://stackoverflow.com/questions/15423500/nginx-showing-blank-php-pages
I will have a play later thanks again, how I found it was google. I too hated the graphics and design of the templates available so went on the hunt, think the word 'responsive' helped me find you

**Comment by shreddedbacon** [comment]
Interesting, what version of raspian are you using?

**Comment by klakka** [comment]
Ahhh hmm the oldest one I think 256Mb??
I'm also sending info to your site (if its working) Nuneaton.raspiweather.com

**Comment by shreddedbacon** [comment]
What about the OS distribution?

**Comment by klakka** [comment]
2015-11-21-raspbian-jessie

**Comment by shreddedbacon** [comment]
Thanks, I'll test around jessie. They may have changed something in jessie that broke my script. 
The last tests that I performed raspian was still on wheezy.

**Comment by klakka** [comment]
Hi mate, I'm struggling with turning the charts to Fahrenheit, I'm sure the widgets will work but the same way of displaying Fahrenheit in the charts and tables throughs up an error:-

2016-01-08 17:59:00:pywws.Template:Unknown processing directive: #temp_f(temp_in)  "%.1f" "-"#
KMH to MPH works fine though.

live site at http://www.micksweather.co.uk

Some of the widgets I would like to make are:-

1) max temp this year
2) min temp this year
3) max wind gust

> At the end of the year I would like a year temp chart too, but hopefully by then ive worked it all out. ;-)
> also noticed you use the degrees symbol rather than `&deg;C (or F)`  or even `&#8451;` or `&#8457;` >for Celsius and Fahrenheit respectively! displays incorrectly in a few browsers if you just use the >degrees symbol
> 
> But just adding this may help:-
> `<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />` adds more characters
> @shreddedbacon SPLIT TO NEW ISSUE: https://github.com/raspiweather/raspiweather/issues/4
> 
> This would be a great addition too:-
> 
> `<meta http-equiv="refresh" content="300">` basically refreshes the page every five minutes
> @shreddedbacon SPLIT TO NEW ISSUE: https://github.com/raspiweather/raspiweather/issues/3

I will be getting a weather station soon too so can play more with the coding

**Comment by shreddedbacon** [comment]
Interesting. I haven't done much with conversions in PYWWS as I'm in Australia and we are pretty much exclusively decimal/celcius. I'll see if there is something I can do to help with it, but if it turns out to be upstream with PYWWS then will need to submit an issue with Jim Easterbrook.

I'll try and get a commit up in the next few days that should allow you to create widgets.

When you say that I've used the degrees symbol, can you let me know where you see it and I'll have a look.

I might make the page refresh an optional thing. Some people don't like auto page refresh.

**Comment by shreddedbacon** [comment]
Looks like the fix for conversions is a bit more complex. You need to use the calc function, with the temperature conversion inside referencing a data table, like this:
`#calc "temp_f(data['temp_out'])" "%.1f" "-"#`

**Comment by shreddedbacon** [comment]
For the charts, you probably want something like this:

{"time":"#idx "%H%M %d/%b"#",
"Temp In":#calc "temp_f(data['temp_in'])" "%.1f" "-"#,
"Temp Out":#calc "temp_f(data['temp_out'])" "%.1f" "-"#,
"Apparent Temp":#calc "temp_f(apparent_temp(data['temp_out'], data['hum_out'], data['wind_ave']))" "%.1f" "-"#}

**Comment by shreddedbacon** [comment]
I've added commit 2cb3fea to fix the python-usb issues to test the nginx blank screen issue in Raspbian Jessie.

**Comment by shreddedbacon** [comment]
I can confirm what you were seeing with the blank page as being related to Debian Jessie and the version of Nginx being used.
I've release a patched commit that should fix the issue for future installations.

Fix for /tmp/weather not appearing:
I changed default tmp directory from /tmp/weather to /apps/weather/tmp and modified configs/weather.ini to use this directory instead as it is already created in the installation.

If you want to try this out, all you need to do is in the web front end, go to PYWWS Settings -> Paths -> and change the working dir to /apps/weather/tmp. The directory should already be created.
