### ISSUE TITLE
X Axis Labels on graphs overlapping on smaller screens

### ISSUE THREAD

**Issue by klakka** [raspiweather/raspiweather#2]
As the title says, this maybe a fix http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/xaxis/labels-autorotation-default/

**Comment by shreddedbacon** [comment]
Ah excellent. I'll look at implementing this.

**Comment by klakka** [comment]
There's also this one http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/xaxis/labels-autorotation-0-90/

**Comment by shreddedbacon** [comment]
Updated the version of highchartsjs that I bundle to 4.2.1 and that has a default feature for responsive labels.
