### ISSUE TITLE
Add option for refreshing dashboard every 5 minutes

### ISSUE THREAD

**Issue by shreddedbacon** [raspiweather/raspiweather#3]
From @klakka:

> This would be a great addition too:-
> 
> basically refreshes the page every five minutes

`<meta http-equiv="refresh" content="300">`

**Comment by shreddedbacon** [comment]
@klakka did you want to have this on the dashboard view only?
I think that's probably the best place for it myself.

**Comment by klakka** [comment]
Yes for the dashboard only, reference the degrees symbol, its every 'Overview' page.

Displays fine on my mobile but Edge displays a black diamond with a question mark. Ive updated a few of my pages and its displaying correctly now

**Comment by shreddedbacon** [comment]
Commit 01b42dad, a423f2acbc6 and dfd7d1af4 implements page refreshing under the same menu where you can change the site name/colour.

I've set it to 0 by default, to enable it specify the number of seconds for the interval.

You will also probably need to run this query in the database manually:
`INSERT INTO `site_info` (`site_item`, `site_value`) VALUES
('site_refresh', '0');`

If you haven't done any changes to code, you should be able to do a git pull and then insert the new record to the database and be good to go.

**Comment by klakka** [comment]
Sorry pal, do you mean copy over the files then go into MySQL and run the query?, not sure what a git pull is.
The only files I have changed are the template and widgets txts and a css file (made the forecast icon central)

**Comment by shreddedbacon** [comment]
If you log in to the pi directly and change to the weather user

`pi:~ $ sudo su - weather`
`weather:~ $ git pull`

Then go into mysql and run the query.

**Comment by shreddedbacon** [comment]
How did you go with this @klakka just want to make sure everything worked properly.

Let me know.

**Comment by klakka** [comment]
Hi sorry for the delay, works a treat really good!!.. Ive just finished install my station now, wow I cant stop comparing with my fathers lol.
