### ISSUE TITLE
Wind Charts (Direction) 60 mins and 24hrs

### ISSUE THREAD

**Issue by klakka** [raspiweather/raspiweather#6]
Very strange goings on when you hover over the chart. So if I hover over the SW section of the chart the info is NNW. Actually that's wrong, if you hover over the chart nothing happens unless you hover over a segment which has info in. If you place the mouse to the left of the chart and move around in the white space you will see the chart info pop up.

**Comment by shreddedbacon** [comment]
I'll have a look into it.

**Comment by shreddedbacon** [comment]
I think this is probably something to do with when I upgraded the highchart version. I'll spend some time on it soon, hopefully its an easy fix.

**Comment by shreddedbacon** [comment]
Commit 39647dcde6a49 fixes this issue. Update the highcharts-more.js to the latest version.
