### ISSUE TITLE
Error on one table template

### ISSUE THREAD

**Issue by klakka** [raspiweather/raspiweather#7]
Hi again,
I've found a couple of errors but I've lost my notes!!.
First one is on one of the tables a couple of the columns are visible when they should be hidden they are missing
<td class="hidden-xs"> 

Second one is Last 24 Hrs, a strange character again see below

Highest gust speed
24 mph 2016/01/27 11:45 GMT 
�
From 09:00 GMT on 26 Jan to 09:00 GMT on 27 Jan 2016 

One more error is the Forecast symbol (so far ive found one that will not display, its missing the word sunny in its name) from the top of my head its something on the lines of wi-day-sunny-overcast.

Ive been waiting for days for the symbol to display ( fixed mine, not my dads)

Mines here (ive played a little bit and still playing)

http://www.build-up.uk

Ian

Quick question regarding names of pages (Is it ok changing the news page name?)

**Comment by shreddedbacon** [comment]
If you edit the template for the 24 hour chart look near the bottom for this line:
`#idx "  <tr><th colspan=\"4\"> </th></tr>" "" "[x, None][loop_count==1]"#`
change it to this
`#idx "  <tr><th colspan=\"4\"></th></tr>" "" "[x, None][loop_count==1]"#`

There is a space between the <th colspan=\"4\"></th> which I think is causing the issue for you.

With regard to changing the page name, you probably can and it would be OK, but I think after seeing what you did I will open a new issue/feature request for it.
As soon as you modify files, you break the git pull/update ability, cause git will complain that you have modified files.

**Comment by shreddedbacon** [comment]
The table that has the headings when in mobile but no data columns is the 7 day template, the <th> columns are missing the attribute to say hide when in mobile view. The following template should fix it.

```
<table class="table table-hover table-striped table-bordered">
<thead>
  <tr>
    <th>24 hours ending</th>
    <th>Temp Day Max</th>
    <th>Temp Night Min</th>
    <th class="hidden-xs">Wind Dir</th>
    <th>Wind Ave</th>
    <th class="hidden-xs">Wind gust</th>  
    <th>Rainfall</th>
  </tr>
</thead>
<tbody>
#timezone local#
#roundtime True#
#daily#
#jump 0#
#loop 7#
  <tr>
    <td>#idx "%Y/%m/%d"#</td>
    <td>#temp_out_max "%.1f<small>°C</small>"#</td>
    <td>#temp_out_min "%.1f<small>°C</small>"#</td>
    <td class="hidden-xs">#wind_dir "%s" "-" "winddir_text(x)"#</td>
    <td>#wind_ave "%.0f <small>mph</small>" "" "wind_mph(x)"#</td>
    <td class="hidden-xs">#wind_gust "%.0f <small>mph</small>" "" "wind_mph(x)"#</td>
    <td>#rain "%0.1f <small>mm</small>"#</td>
  </tr>
#jump -1#
#endloop#
</tbody>
</table>
```

**Comment by klakka** [comment]
Thanks, I've updated the mobile view already, thought I would flag it up. A few other requests would be Google Analytics and meta data would be good. If you type the address into google you can see how it displays, also noticed Google kept crawling the site today, every 3hrs!!

**Comment by klakka** [comment]
Ps I've messed with the forecast area a bit too, so I guess I will be playing with text editors from now on in lol

**Comment by shreddedbacon** [comment]
I noticed you had done more changes to it. I mainly built it just for my own use, so didn't think about a lot of things like google analytics or meta data.

With google crawling the site, I'm not too familiar with bot search restrictions. But you might be able to put a robots.txt file in the public_html folder with some config in that. I don't know too much about it though, so you might have to google that.
